services:
    redis:
      image: redis:alpine
      container_name: redis
      restart: unless-stopped
      expose:
        - "6379"
      networks:
        - traefik-proxy
       
networks:
  traefik-proxy:
    external: true
